### ISSUE TITLE
[BUG] Embed with link title returns `AttributeError: 'NoneType' object has no attribute 'split'`

### ISSUE THREAD

**Issue by ooker777** [Mara-Li/mkdocs_embed_file_plugins#5]
Say my `mkdocs.yaml` is:
```yaml
site_name: test
plugins:
  - embed_file:
      callouts: true
```

and in the docs folder I have a file `a.md`. If its content is:
```markdown
![](./b.md)
```
then the build works. However if the content is:
```markdown
![b](./b.md)
```
then it returns this error:
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\QC
           supplements\Code\Websites\CW-obsidian-quan-ly-du-an-va-cong-cu-nghi\site
WARNING -  Doc file 'a.md' contains a relative link
           './b.md', but the target 'b.md' is not found
           among documentation files.
ERROR   -  Error building page 'a.md': 'NoneType'
           object has no attribute 'split'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 349, in build
    _build_page(
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 235, in _build_page
    output = config.plugins.on_post_page(output, page=page, config=config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\plugins.py", line 586, in on_post_page
    return self.run_event('post_page', output, page=page, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs_embed_file_plugins\plugin.py", line 201, in on_post_page
    soup = cite(
           ^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs_embed_file_plugins\plugin.py", line 77, in cite
    quote = convert_links_if_markdown(quote, (docs, url, md_link_path))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs_embed_file_plugins\src\links_correction.py", line 23, in convert_links_if_markdown
    url_blog_path = [x for x in url_blog.split("/") if len(x) > 0]
                                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

What does this line do?

**Comment by Mara-Li** [comment]
Can't repo.

**Comment by pedrotrschneider** [comment]
I can confirm, I'm also getting this error. Using wikilinks format.
The funny part is, it only gives me an error when I use `mkdocs build`. `mkdocs serve` works just fine.

**Comment by Mara-Li** [comment]
Thank you, I will check with mkdocs build. 
Pretty strange error.

**Comment by Mara-Li** [comment]
Okay, I found the problem : you forgot to define the site_url.
I raise an exception in the build process to advertise about this error.

**Comment by ooker777** [comment]
hmm, why would that make the error? Also, which part of your code generate the fix? https://github.com/ObsidianPublisher/mkdocs-embed_file-plugin/commit/3b3238b71204469828b7d8a8023c2cb89054bedc

**Comment by Mara-Li** [comment]
The scripts can't work without site_url and mkdocs doesn't like that either. 
Just put the `site_url` in your mkdocs.yml, please…

**Comment by pedrotrschneider** [comment]
Oh, nice! I had no idea mkdocs didn't like that. Thanks a lot for the quick response!
